set.seed(666)
library(ISLR)
library(boot)
library(ggplot2)
attach(Wage)

cv_test_error = rep(NA, 10)

for (i in 1:10)
{
    glm.fit = glm(wage ~ poly(age, i), data = Wage)
    cv_test_error[i] = cv.glm(Wage, glm.fit, K = 10)$delta[2]
}

degrees_of_freedom = 1:10
plot(ggplot() + geom_line(data = data.frame(degrees_of_freedom, cv_test_error),
aes(degrees_of_freedom, cv_test_error), col = "black") +
geom_point(data = data.frame(degrees_of_freedom, cv_test_error),
aes(degrees_of_freedom, cv_test_error), col = "red") +
geom_hline(aes(yintercept = min(cv_test_error) + sd(cv_test_error[2:10])),
linetype = "dashed", col = "red") +
geom_hline(aes(yintercept = min(cv_test_error) - sd(cv_test_error[2:10])),
linetype = "dashed", col = "red") +
geom_text(x = 7, y = 1601, aes(label = label), data.frame(label = c("Standard error of the cv test error generated by models with 2-9 variables"))) +
geom_text(x = 7, y = 1587, aes(label = label), data.frame(label = c("Standard error of the cv test error generated by models with 2-9 variables"))) +
coord_cartesian(ylim = c(1580, 1680),xlim = c(1, 11)) +
scale_x_continuous(breaks = degrees_of_freedom, labels = degrees_of_freedom))

fit1 = lm(wage ~ poly(age, 1), data = Wage)
fit2 = lm(wage ~ poly(age, 2), data = Wage)
fit3 = lm(wage ~ poly(age, 3), data = Wage)
fit4 = lm(wage ~ poly(age, 4), data = Wage)
fit5 = lm(wage ~ poly(age, 5), data = Wage)
fit6 = lm(wage ~ poly(age, 6), data = Wage)
fit7 = lm(wage ~ poly(age, 7), data = Wage)
fit8 = lm(wage ~ poly(age, 8), data = Wage)
fit9 = lm(wage ~ poly(age, 9), data = Wage)
fit10 = lm(wage ~ poly(age, 10), data = Wage)
print(anova(fit1, fit2, fit3, fit4, fit5, fit6, fit7, fit8, fit9, fit10))

data = data.frame(x = age, y = wage)
plot(ggplot(data) + geom_point(data = data, aes(x = x, y = y), alpha = .9, colour = "#56B4E9") +
geom_smooth(aes(x = x, y = y), method ='lm', formula = y ~ poly(x, 3), colour = "#D55E00") + xlab("Age") + ylab("Wage"))

cv_test_error = rep(NA, 10)
for (i in 2:10)
{
  Wage$age.cuts = cut(age, i)
  lm.fit = glm(wage ~ age.cuts, data = Wage)
  cv_test_error[i] = cv.glm(Wage, lm.fit, K = 10)$delta[2]
}

cuts = 1:10
plot(ggplot() + geom_line(data = data.frame(cuts, cv_test_error),
aes(cuts, cv_test_error), col = "black") +
geom_point(data = data.frame(cuts, cv_test_error),
aes(cuts, cv_test_error), col = "red") +
coord_cartesian(xlim = c(2, 10)) +
scale_x_continuous(breaks = cuts, labels = cuts))

lm.fit = glm(wage ~ cut(age, 8), data = Wage)
x_range = range(Wage$age)
x_grid = seq(from = x_range[1], to = x_range[2])
lm.pred = predict(lm.fit, data.frame(age = x_grid))

data = data.frame(x = age, y = wage)
step_f = data.frame(x = x_grid, y = lm.pred)
plot(ggplot() + geom_point(data = data, aes(x = x, y = y), alpha = .8, colour = "#56B4E9") +
geom_line(data = step_f, aes(x = x, y = y) , colour = "#D55E00", size = 1) + xlab("Age")
+ ylab("Wage"))
